name: zb

on:
  schedule:
    - cron: '0 */12 * * *'  # 每12个小时的第 0 分钟运行
  workflow_dispatch:
    分支:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2
    
      - name: Set up Python
        uses: actions/setup-python@v2
        with:
          python-version: 3.x

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
      - name: Install bs4
        run: pip3 install bs4
      - name: Install playwright
        run: pip3 install playwright
      - name: Install requests
        run: pip3 install requests     
      - name: Install playwright install
        run: playwright install
      - name: Install datetime
        run: pip install datetime

      - name: Run ZB1
        run: python ${{ github.workspace }}/main.py
        
      # - name: Run zb2
      #   run: python ${{ github.workspace }}/zb2.py

      - name: 提交更改
        run: |
          git config --local user.email "luoyexp@163.com"
          git config --local user.name "hndxzb"
          git add .
          git commit *.txt -m "Add generated file"
          # git commit *.m3u -m "Add generated file"
          #git pull --rebase
          git push -f
